/* Token-exact oracle harness for odin-infer.
   Loads a fixture produced by gen_fixture.py (HF transformers, Qwen3 fp16
   teacher-forcing) and compares it against engine_forward on the same GGUF
   and same prompts. Reports per-prompt top-1 agreement, max-abs and mean-abs
   logit diff, and top-5 overlap, then an aggregate PASS/WARN/FAIL verdict.

   Why statistical (not bit-exact): we use third-party GGUF quantization
   (Q4_K_M etc.), so HF fp16 vs quantized logits cannot match bit-exact.
   colibri gets 32/32 because they own their int4 container — we don't.

   Subcommands:
     run  <model.gguf> <fixture.bin> [--metal]   run comparison
     dump <fixture.bin> [prompt_idx]             inspect a fixture

   Run (from repo root):
     odin run oracle_harness/oracle.odin -file -- \
       run Qwen3-0.6B-Q4_K_M.gguf oracle_harness/fixtures/qwen3-0.6b-q4km.bin \
       -collection:ggml=. -collection:infer=. \
       -collection:tokenizer=. -collection:sampler=.

   Binary format (little-endian, generated by gen_fixture.py):
     magic      : u32 = 0x4F524331  ('ORC1')
     vocab      : u32
     n_prompts  : u32
     per prompt:
        prompt_len : u32
        tokens     : [u32; prompt_len]
        logits     : [f16; vocab * prompt_len]   row-major [pos][vocab]
*/

package oracle

import "core:fmt"
import "core:math"
import "core:os"
import infer "infer:infer"

MAGIC :: u32(0x4F524331) // 'O','R','C','1' little-endian

// ---- tolerance policy (v0 — calibrate after first end-to-end run) ----
TOP1_PASS_PCT :: f32(80.0)
TOP1_WARN_PCT :: f32(65.0)
MAXDIFF_PASS  :: f32(6.0)
MAXDIFF_WARN  :: f32(12.0)
TOP5_PASS_PCT :: f32(60.0)

Prompt_View :: struct {
	tokens: []u32,
	logits_offset: int, // byte offset into Fixture.data
	n_positions:  int,
}

Fixture :: struct {
	data:      []u8, // owned
	vocab:     u32,
	n_prompts: u32,
	prompts:   []Prompt_View,
}

Per_Position :: struct {
	top1_match:    bool,
	max_abs:       f32,
	mean_abs:      f32,
	top5_overlap:  int, // 0..5
}

Prompt_Result :: struct {
	idx:        int,
	n_positions: int,
	positions:  []Per_Position,
	// aggregates
	top1_count: int,
	max_abs:    f32,
	mean_abs:   f32,
	top5_total: int,
	verdict:    string,
}

// ---------- little-endian readers ----------

u32_le :: proc(b: []u8, off: int) -> u32 {
	return u32(b[off]) | (u32(b[off + 1]) << 8) | (u32(b[off + 2]) << 16) | (u32(b[off + 3]) << 24)
}

f16_le :: proc(b: []u8, off: int) -> f32 {
	h := transmute(f16)(u16(b[off]) | (u16(b[off + 1]) << 8))
	return f32(h)
}

// ---------- fixture loader ----------

load_fixture :: proc(path: string) -> (Fixture, bool) {
	f: Fixture
	data, err := os.read_entire_file_from_path(path, context.allocator)
	if err != os.ERROR_NONE {
		fmt.eprintf("oracle: cannot read %s (err=%v)\n", path, err)
		return f, false
	}
	if len(data) < 12 {
		fmt.eprintf("oracle: fixture too small (%d bytes)\n", len(data))
		return f, false
	}
	magic := u32_le(data, 0)
	if magic != MAGIC {
		fmt.eprintf("oracle: bad magic 0x%08x (expected 0x%08x)\n", magic, MAGIC)
		return f, false
	}
	f.data = data
	f.vocab = u32_le(data, 4)
	f.n_prompts = u32_le(data, 8)
	f.prompts = make([]Prompt_View, f.n_prompts)

	cursor := 12
	for i in 0 ..< f.n_prompts {
		if cursor + 4 > len(data) {
			fmt.eprintf("oracle: truncated at prompt %d header\n", i)
			return f, false
		}
		plen := u32_le(data, cursor)
		cursor += 4
		tokens_bytes := int(plen) * 4
		logits_bytes := int(plen) * int(f.vocab) * 2
		if cursor + tokens_bytes + logits_bytes > len(data) {
			fmt.eprintf("oracle: truncated at prompt %d body\n", i)
			return f, false
		}
		// tokens: copy out so caller can read without manual LE decoding each time
		tokens := make([]u32, plen)
		for t in 0 ..< int(plen) {
			tokens[t] = u32_le(data, cursor + t * 4)
		}
		f.prompts[i] = Prompt_View {
			tokens = tokens,
			logits_offset = cursor + tokens_bytes,
			n_positions = int(plen),
		}
		cursor += tokens_bytes + logits_bytes
	}
	return f, true
}

free_fixture :: proc(f: ^Fixture) {
	for i in 0 ..< len(f.prompts) {
		delete(f.prompts[i].tokens)
	}
	delete(f.prompts)
	delete(f.data)
}

// ---------- comparison core ----------

// Track top-k (k=5) via linear scan with a small fixed-size buffer.
// For 151k vocab this is faster than full sort and allocation-free.
top5 :: proc(logits: []f32, out: ^[5]u32) {
	vals := [5]f32{-math.F32_MAX, -math.F32_MAX, -math.F32_MAX, -math.F32_MAX, -math.F32_MAX}
	idxs := [5]u32{0, 0, 0, 0, 0}
	for v, i in logits {
		if v <= vals[4] { continue }
		// insert into sorted [0..4] descending
		slot := 4
		for slot > 0 && v > vals[slot - 1] { slot -= 1 }
		// shift down (must iterate downward to avoid overwrite-before-read)
		j := 4
		for j > slot {
			vals[j] = vals[j - 1]
			idxs[j] = idxs[j - 1]
			j -= 1
		}
		vals[slot] = v
		idxs[slot] = u32(i)
	}
	for i in 0..<5 { out[i] = idxs[i] }
}

set_contains :: proc(s: [5]u32, n: int, x: u32) -> bool {
	for i in 0 ..< n {
		if s[i] == x { return true }
	}
	return false
}

compare_prompt :: proc(e: ^infer.Engine, fx: ^Fixture, pv: ^Prompt_View) -> Prompt_Result {
	res: Prompt_Result
	res.idx = -1
	res.n_positions = pv.n_positions
	res.positions = make([]Per_Position, pv.n_positions)

	argmax := proc(logits: []f32) -> u32 {
		am: u32 = 0
		best: f32 = logits[0]
		for v, i in logits {
			if v > best { best = v; am = u32(i) }
		}
		return am
	}

	for pos in 0 ..< pv.n_positions {
		token := pv.tokens[pos]
		cpu_logits := infer.engine_forward(e, int(token), pos)
		if len(cpu_logits) != int(fx.vocab) {
			fmt.eprintf("oracle: vocab mismatch at pos %d (got %d, fixture %d)\n",
				pos, len(cpu_logits), fx.vocab)
			res.verdict = "FAIL"
			return res
		}
		// reference logits row: pv.logits_offset + pos * vocab * 2 bytes
		row_off := pv.logits_offset + pos * int(fx.vocab) * 2

		max_abs := f32(0.0)
		sum_abs := f32(0.0)
		// argmax over reference
		ref_am: u32 = 0
		ref_best: f32 = f16_le(fx.data, row_off)
		for v in 0 ..< int(fx.vocab) {
			cpu := cpu_logits[v]
			ref := f16_le(fx.data, row_off + v * 2)
			d := math.abs(cpu - ref)
			if d > max_abs { max_abs = d }
			sum_abs += d
			if ref > ref_best { ref_best = ref; ref_am = u32(v) }
		}
		mean_abs := sum_abs / f32(fx.vocab)

		cpu_am := argmax(cpu_logits)
		cpu_top5: [5]u32
		top5(cpu_logits, &cpu_top5)
		ref_top5 := top5_of_ref(fx.data[row_off:row_off + int(fx.vocab) * 2])

		overlap := 0
		for i in 0 ..< 5 {
			if set_contains(cpu_top5, 5, ref_top5[i]) { overlap += 1 }
		}

		res.positions[pos] = Per_Position {
			top1_match = (cpu_am == ref_am),
			max_abs = max_abs,
			mean_abs = mean_abs,
			top5_overlap = overlap,
		}
		res.top1_count += (cpu_am == ref_am ? 1 : 0)
		res.top5_total += overlap
		if max_abs > res.max_abs { res.max_abs = max_abs }
		res.mean_abs += mean_abs
	}
	res.mean_abs /= f32(pv.n_positions)
	verdict_of(&res)
	return res
}

// top-5 over a raw f16 byte blob (no temp f32 slice alloc).
top5_of_ref :: proc(b: []u8) -> [5]u32 {
	vals := [5]f32{-math.F32_MAX, -math.F32_MAX, -math.F32_MAX, -math.F32_MAX, -math.F32_MAX}
	idxs := [5]u32{0, 0, 0, 0, 0}
	n := len(b) / 2
	for i in 0 ..< n {
		v := f16_le(b, i * 2)
		if v <= vals[4] { continue }
		slot := 4
		for slot > 0 && v > vals[slot - 1] { slot -= 1 }
		j := 4
		for j > slot {
			vals[j] = vals[j - 1]
			idxs[j] = idxs[j - 1]
			j -= 1
		}
		vals[slot] = v
		idxs[slot] = u32(i)
	}
	return idxs
}

verdict_of :: proc(r: ^Prompt_Result) {
	top1_pct := f32(r.top1_count) / f32(r.n_positions) * 100.0
	top5_avg_pct := f32(r.top5_total) / f32(r.n_positions) / 5.0 * 100.0
	r.verdict = "PASS"
	if top1_pct < TOP1_WARN_PCT || r.max_abs > MAXDIFF_WARN || top5_avg_pct < 30.0 {
		r.verdict = "FAIL"
	} else if top1_pct < TOP1_PASS_PCT || r.max_abs > MAXDIFF_PASS || top5_avg_pct < TOP5_PASS_PCT {
		r.verdict = "WARN"
	}
}

// ---------- printing ----------

print_result_table :: proc(results: []Prompt_Result) {
	fmt.println("\n┌─────┬──────────┬──────────┬──────────┬──────────┬────────┐")
	fmt.println("│  #  │ top-1 %  │ top-5 %  │ max_abs  │ mean_abs │ verdict│")
	fmt.println("├─────┼──────────┼──────────┼──────────┼──────────┼────────┤")
	for r in results {
		top1_pct := f32(r.top1_count) / f32(r.n_positions) * 100.0
		top5_pct := f32(r.top5_total) / f32(r.n_positions) / 5.0 * 100.0
		fmt.printfln("│ %3d │ %6.2f%%  │ %6.2f%%  │ %8.3f │ %8.4f │  %-4s  │",
			r.idx, top1_pct, top5_pct, r.max_abs, r.mean_abs, r.verdict)
	}
	fmt.println("└─────┴──────────┴──────────┴──────────┴──────────┴────────┘")
}

print_aggregate :: proc(results: []Prompt_Result, vocab: u32, use_metal: bool) {
	n_prompts := len(results)
	total_pos := 0
	total_top1 := 0
	total_top5 := 0
	worst_max := f32(0)
	sum_mean := f32(0)
	verdict := "PASS"
	for r in results {
		total_pos += r.n_positions
		total_top1 += r.top1_count
		total_top5 += r.top5_total
		if r.max_abs > worst_max { worst_max = r.max_abs }
		sum_mean += r.mean_abs
		if r.verdict == "FAIL" { verdict = "FAIL" }
		else if r.verdict == "WARN" && verdict != "FAIL" { verdict = "WARN" }
	}
	top1_pct := f32(total_top1) / f32(total_pos) * 100.0
	top5_pct := f32(total_top5) / f32(total_pos) / 5.0 * 100.0
	avg_mean := sum_mean / f32(n_prompts)
	fmt.printfln(
		"\nAggregate (%s): top1=%.2f%%  top5=%.2f%%  worst_max_abs=%.3f  avg_mean_abs=%.4f  verdict=%s",
		use_metal ? "Metal" : "CPU", top1_pct, top5_pct, worst_max, avg_mean, verdict)
	fmt.printfln("  vocab=%d  prompts=%d  positions=%d", vocab, n_prompts, total_pos)
}

// ---------- dump subcommand ----------

run_dump :: proc(args: []string) -> int {
	if len(args) < 1 {
		fmt.eprintln("usage: oracle dump <fixture.bin> [prompt_idx]")
		return 1
	}
	fx, ok := load_fixture(args[0])
	if !ok { return 1 }
	defer free_fixture(&fx)

	fmt.printfln("fixture: %s", args[0])
	fmt.printfln("  magic=0x%08x  vocab=%d  n_prompts=%d  size=%.2f MB",
		MAGIC, fx.vocab, fx.n_prompts, f64(len(fx.data)) / 1024.0 / 1024.0)

	only_idx := -1
	if len(args) >= 2 {
		only_idx = int(parse_int_or(args[1], -1))
	}

	for i in 0 ..< int(fx.n_prompts) {
		if only_idx >= 0 && i != only_idx { continue }
		pv := &fx.prompts[i]
		fmt.printfln("\n[%d] len=%d  tokens:", i, pv.n_positions)
		// print token ids
		fmt.print("  ids: ")
		for t in 0 ..< int(pv.n_positions) {
			fmt.printf("%d ", pv.tokens[t])
			if t > 0 && t % 16 == 0 { fmt.println() ; fmt.print("      ") }
		}
		fmt.println()
		// top-5 of last position
		if pv.n_positions > 0 {
			last_off := pv.logits_offset + (pv.n_positions - 1) * int(fx.vocab) * 2
			t5 := top5_of_ref(fx.data[last_off:last_off + int(fx.vocab) * 2])
			fmt.print("  last-pos top-5: ")
			for k in 0 ..< 5 {
				v := f16_le(fx.data, last_off + int(t5[k]) * 2)
				fmt.printf("[%d]=%.3f ", t5[k], v)
			}
			fmt.println()
		}
	}
	return 0
}

parse_int_or :: proc(s: string, def: int) -> int {
	v, ok := strconv_parse_int(s)
	if !ok { return def }
	return v
}

// tiny shim — core:strconv has parse_int but signature varies by Odin version
strconv_parse_int :: proc(s: string) -> (int, bool) {
	if len(s) == 0 { return 0, false }
	neg := false
	i := 0
	if s[0] == '-' { neg = true; i = 1 }
		else if s[0] == '+' { i = 1 }
	v: int = 0
	for i < len(s) {
		c := s[i]
		if c < '0' || c > '9' { return 0, false }
		v = v * 10 + int(c - '0')
		i += 1
	}
	return neg ? -v : v, true
}

// ---------- run subcommand ----------

run_run :: proc(args: []string) -> int {
	if len(args) < 2 {
		fmt.eprintln("usage: oracle run <model.gguf> <fixture.bin> [--metal]")
		return 1
	}
	model_path := args[0]
	fixture_path := args[1]
	use_metal := false
	for i in 2 ..< len(args) {
		if args[i] == "--metal" { use_metal = true }
	}

	fx, ok := load_fixture(fixture_path)
	if !ok { return 1 }
	defer free_fixture(&fx)
	fmt.printfln("fixture loaded: vocab=%d prompts=%d", fx.vocab, fx.n_prompts)

	cores := os.get_processor_core_count()
	e, load_ok := infer.engine_load(model_path, infer.Engine_Opts{
		max_ctx = 4096,
		use_metal = use_metal,
		num_threads = cores,
	})
	if !load_ok {
		fmt.eprintln("oracle: engine_load failed")
		return 1
	}
	defer infer.engine_destroy(&e)
	defer infer.destroy_matmul_pool()

	cfg := infer.engine_config(&e)
	if cfg.vocab_size != int(fx.vocab) {
		fmt.eprintf("oracle: engine vocab (%d) != fixture vocab (%d)\n",
			cfg.vocab_size, fx.vocab)
		return 1
	}
	fmt.printfln("engine loaded: vocab=%d  metal=%v  threads=%d",
		cfg.vocab_size, use_metal, cores)

	results := make([]Prompt_Result, fx.n_prompts)
	for i in 0 ..< int(fx.n_prompts) {
		fmt.printfln("\n[.%d/%d] comparing prompt (len=%d)…",
			i + 1, fx.n_prompts, fx.prompts[i].n_positions)
		r := compare_prompt(&e, &fx, &fx.prompts[i])
		r.idx = i
		results[i] = r
		// incremental
		top1_pct := f32(r.top1_count) / f32(r.n_positions) * 100.0
		fmt.printfln("    top1=%.2f%%  max_abs=%.3f  verdict=%s",
			top1_pct, r.max_abs, r.verdict)
		delete(r.positions)
	}

	print_result_table(results)
	print_aggregate(results, fx.vocab, use_metal)

	// final exit code: 0 PASS, 1 WARN, 2 FAIL
	verdict := "PASS"
	for r in results {
		if r.verdict == "FAIL" { verdict = "FAIL"; break }
		if r.verdict == "WARN" && verdict != "FAIL" { verdict = "WARN" }
	}
	delete(results)
	if verdict == "PASS" { return 0 }
	if verdict == "WARN" { return 1 }
	return 2
}

// ---------- entry ----------

main :: proc() {
	args := os.args
	if len(args) < 2 {
		fmt.eprintln("usage:")
		fmt.eprintln("  oracle run  <model.gguf> <fixture.bin> [--metal]")
		fmt.eprintln("  oracle dump <fixture.bin> [prompt_idx]")
		os.exit(1)
	}
	sub := args[1]
	rest := args[2:]
	switch {
	case sub == "run":
		os.exit(run_run(rest))
	case sub == "dump":
		os.exit(run_dump(rest))
	case:
		fmt.eprintf("oracle: unknown subcommand %q\n", sub)
		os.exit(1)
	}
}
